
version: 2

models:
  - name: station
    description: "Contains all bike share stations in both NY and SF"
    columns:
      - name: station_key
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stationlocation
    description: "A starter dbt model"
    columns:
      - name: station_key
        description: "Contains the longitude and lattitude locations for each station"
        tests:
          - unique
          - not_null
